### PR TITLE
Prefix SKU from model field or default to using the source on config as a string

### PR DESCRIPTION
**Pull request by talelmishali**
Hey! Came across the need to default the SKU prefix to a predefined string and not necessarily based on a field from the model.

-Check if the specified source field in the config file exists on the model, if not then use the source field as a string to prefix the SKU.

### CODE REVIEW

**Comment by nickfls** [comment]
I would rather create SKU generator contract and offer an alternative implementation, but that is just me.
Let me check in a few

**Comment by cyrillkalita** [comment]
@talelmishali  you are not forgotten; you just reminded me of the original plan. Hold on tight, a new version is coming up

**Comment by cyrillkalita** [comment]
@talelmishali take a look at #13 
`SkuGenerator` is now fully customizable; you can just plug in your own login, either by extending or replacing completely.

**Comment by talelmishali** [comment]
A very elegant solution, working great.
Thanks!

**Pull request closed without merging**
